- hosts: all
  vars:
    probe_name: 'RPi5000s'
    probe_location: 'Umich'
    tests: [
      {
        name: 'example_test_rtt',
        type: 'rtt',
        dest: 'www.umich.edu'
      },
      {
        name: 'example_test_latency',
        type: 'latency',
        dest: 'perfsonar-bin-arbl.umnet.umich.edu'
      }
    ]
    SSID: [
      {
        name: "MWireless_profile",
        SSID: "MWireless",
        channels: "MWireless_channels",
        channel_mismatch_warning: "true",
        channel_mismatch_connect: "false",
        min_signal: -73,
        min_qualifying: 5, 
        Auth: "true",
        type: "User",
        UID: "fakeUID",
        Password: "fakepassword",
        paranoid: "false",
        pscheduler_restart: "false",
        apache_restart: "false",
        postgres_restart: "false",
        wait_time: 0
      },
      {
        name: "Eduroam_profile",
        SSID: "eduroam",
        channels: "Eduroam_channels",
        channel_mismatch_warning: "true",
        channel_mismatch_connect: "false",
        min_signal: -65,
        min_qualifying: 5, 
        Auth: "true",
        type: "User",
        UID: "fakeUID",
        Password: "fakepassword",
        paranoid: "false",
        pscheduler_restart: "false",
        apache_restart: "false",
        postgres_restart: "false",
        wait_time: 0
      }

    ]

  tasks:
    - name: Ansible Template Example
      template:
        src: template.j2
        dest: config.json